const Data  = {
  "data":[
    {id: 'MrmwUmYWnL0WY'},
    {id: 'YgmczzYWY4DTO'},
    {id: 'zCfeMBYXjY9yM'},
    {id: '7bVRxNQHN34Va'},
    {id: 'yoJC2wQqhXpm97vdeg'},
    {id: 'pPWlioTBAc6sw'},
    {id: 'xT8qBjRI2PyQuB4T2U'},
    {id: 'TNZr6CvvK1Q1W'},
    {id: 'l2RaPhzQeY4ODghNK'},
    {id: '74JdygfvYRXS8'},
    {id: 'hFu0gS4pFKBH2'},
    {id: 'rPxbtwW4sPbQk'},
    {id: 'Mh3g6QEYSh12E'},
    {id: 'ysEQv6m6ONPR6'},
    {id: '13GQOpAWeaHPG0'},
    {id: 'utcO3n0nPR3UY'},
    {id: '3G8p25shRFZ2E'},
    {id: 'uODVCyIDDm8sU'},
    {id: 'hbtDTGsRMb3sA'},
    {id: 'ZCXB6g8eN2myI'},
    {id: 'Gy3icSyDqQhO'},
    {id: 'BOvINh5lD1ZLy'},
    {id: 'jfxk3En6eBNTO'},
    {id: 'TzFvUWR7AnBza'},
    {id: '13Or1SYzuMseje'},
    {id: 'moPfPzCiqF9Is'},
    {id: 'JjE8gp1Y3XyVi'},
    {id: '7aDBkfSxJNPoY'},
    {id: 'Eft4SRbVPUVeE'},
    {id: 'TA5xnI9WvBL20'},
    {id: 'WT5bIFhzhgpYA'},
    {id: 'lBOdoLyejuuoU'},
    {id: 'UK6DXVYau1R4s'},
    {id: '4oIQ49OuzWnx6'},
    {id: '2gs7BUnZlDSJa'},
    {id: '9gSwBGNqBDw1G'},
    {id: 'coz60uXkyULja'},
    {id: 'h96JgdHSheT04'},
    {id: 'qVE2BWoSFH2PC'},
    {id: 'KxFB0Tv4arQ2I'},
    {id: 'QmG05jRidQnks'},
    {id: 'doZL3RfFprkR2'},
    {id: 'REj5ynn66Tmz6'},
    {id: 'slkHx1GJNYMYE'},
    {id: 'Lprb1IdZyfNRu'},
    {id: 'Hn9td7Kh31xio'},
    {id: 'osaOzAgIQx1y8'},
    {id: 'qOV7tVn1B7NkI'},
    {id: 'GKSNQKQlQ3du0'},
    {id: 'xwpQjH4HG4EMw'},
    {id: 'Jm4UbTjSHq0aQ'},
  ]
}
   export default Data;