const Data  = {
  "data":[
    {id: 'MrmwUmYWnL0WY'},
    {id: 'YgmczzYWY4DTO'},
    {id: 'zCfeMBYXjY9yM'},
    {id: '7bVRxNQHN34Va'},
    {id: 'yoJC2wQqhXpm97vdeg'},
    {id: 'pPWlioTBAc6sw'},
    {id: 'xT8qBjRI2PyQuB4T2U'},
    {id: 'TNZr6CvvK1Q1W'},
    {id: 'l2RaPhzQeY4ODghNK'},
    {id: '74JdygfvYRXS8'},
    {id: 'hFu0gS4pFKBH2'},
    {id: 'rPxbtwW4sPbQk'},
    {id: 'Mh3g6QEYSh12E'},
    {id: 'ysEQv6m6ONPR6'},
    {id: '13GQOpAWeaHPG0'},
    {id: 'utcO3n0nPR3UY'},
    {id: '3G8p25shRFZ2E'},
    {id: 'uODVCyIDDm8sU'},
    {id: 'hbtDTGsRMb3sA'},
    {id: 'ZCXB6g8eN2myI'},
    {id: 'Gy3icSyDqQhO'},
    {id: 'BOvINh5lD1ZLy'},
    {id: 'jfxk3En6eBNTO'},
    {id: 'TzFvUWR7AnBza'},
    {id: '13Or1SYzuMseje'},
    {id: 'moPfPzCiqF9Is'},
    {id: 'JjE8gp1Y3XyVi'},
    {id: '7aDBkfSxJNPoY'},
    {id: 'Eft4SRbVPUVeE'},
    {id: 'TA5xnI9WvBL20'},
    {id: 'WT5bIFhzhgpYA'},
    {id: 'lBOdoLyejuuoU'},
    {id: 'UK6DXVYau1R4s'},
    {id: '4oIQ49OuzWnx6'},
    {id: '2gs7BUnZlDSJa'},
    {id: '9gSwBGNqBDw1G'},
    {id: 'coz60uXkyULja'},
  ]
}
   export default Data;